### ISSUE TITLE
半包问题

### ISSUE THREAD

**Issue by oldshipmaster** [dawnbreaks/NettyRPC#3]
博主你好：
    我在看你的nettyrpc这个框架的时候，发现其中用到的为自定义解码器ByteToMessageDecoder，据我所知，这个解码器，只是自己重写方法后，自己实现，将字节转对象。但是并没有处理半包问题，请问博主是如何规避半包问题的？麻烦花点时间告知一下，不胜感激！

**Comment by dawnbreaks** [comment]
github的issue不是用来讨论这个的。 我也不是博主。
