### ISSUE TITLE
Proper LICENSE

### ISSUE THREAD

**Issue by ctubbsii** [dawnbreaks/NettyRPC#4]
I'm reluctant to use your project, because it doesn't have a proper license on the project. It just says "It is totally free", but that can meant different things to different people, and doesn't address redistribution rights, etc.

Could you update the license to specify a well-known one, which has respect in the open source work? If you want a minimal license, you could select the MIT or BSD licenses, or if you want to explicitly communicate information about patents or contributions but still be very permissive, you could select the Apache License 2.0.

Whatever you select, I think the statement "it is totally free" is more of a deterrent to use than what you probably intended.

**Comment by dawnbreaks** [comment]
Hi, i have updated the license to use Apache License 2.0. Thanks very much.

**Comment by ctubbsii** [comment]
Thanks!
